### ISSUE TITLE
"Could not build wheels for greenlet" error

### ISSUE THREAD

**Issue by Waffle3000n1** [enzok/CAPEsolo#1]
After "pip install gevent-[version].whl" if the following error is generated.

<img width="423" alt="Could not build wheels for greenlet - error" src="https://github.com/enzok/CAPEsolo/assets/171841937/aadb2d83-52ea-4655-9925-dd0b72391af9">

To resolve it a version of Microsoft Visual C++ 14.0 or greater is required. You can select this under Installation Details >> Optional.
To download it the following URL is provided in the code (seen in the image above);

https://visualstudio.microsoft.com/visual-cpp-build-tools/

<img width="740" alt="Microsoft Visual C++ 14 0 or greater" src="https://github.com/enzok/CAPEsolo/assets/171841937/2d199542-3430-4b21-80ed-2527f159c3e8">

If the build tool is already installed then the following will resolve the issue

set DISTUTILS_USE_SDK=1

<img width="889" alt="Setting  distutils msvccompiler" src="https://github.com/enzok/CAPEsolo/assets/171841937/012128a0-5004-4d74-a624-4b03ac05e07c">

see more documentation here, https://docs.python.org/3.11/distutils/apiref.html

**Comment by enzok** [comment]
Thanks for the feedback. It appears I must have had greenlet in my pip cache when testing. I have added a greenlet wheel file in extras and updated the Readme instructions. I have also updated the release file with the latest commits. Let me know if this resolves the issue.
