### ISSUE TITLE
capesolo.exe installed under Scripts folder

### ISSUE THREAD

**Issue by fanzhefu** [enzok/CAPEsolo#2]
I have no problem to install capesolo on both 64bit and 32 bit python and also greenlet and gevent installed with solo, no need extra pip install.

just little thing here:
"Alternatively, create a shortcut to CAPEsolo.exe, which will be in the same location as your python.exe file."
for myslef, the capesolo.exe installed under Scripts folder

**Comment by fanzhefu** [comment]
Could you please add a link to "see CAPE guest guide for details."

**Comment by enzok** [comment]
The install will not work without MS Build Tools. By providing the wheel files for gevent and greenlet we are removing the need for the build tools which are over 6GB in size. You are certainly free to build in your environment. However please note that the analyzer will not work with 64-bit Python. 

I will update the instructions with Scripts path and link to guide. Thanks.

**Comment by enzok** [comment]
Fixed in https://github.com/enzok/CAPEsolo/commit/67cde2dec386b2f8e620a3f0ca056e6fee176411.
