### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by Waffle3000n1** [enzok/CAPEsolo#3]
Was able to take Snap shot successfully, and complete all the steps prior.

When launching capesolo in CLI as Administrator generated the following error

![CAPEsolo did not run](https://github.com/enzok/CAPEsolo/assets/171841937/5a039a43-7d24-45c1-82ae-714d8a8c2152)

Downloaded MS Build Tools to open CAPEsolo

Alternatively, found additional fixes. They are as follows;

pip install pywin32==300

--OR--

python.exe -m pip install --upgrade pip

As it should be noted, throughout the first stage of installing wheels, CLI does recommend updating the python.

![CLI notice to update python](https://github.com/enzok/CAPEsolo/assets/171841937/75bd797a-22f9-4a52-b318-a556aaa1a909)

more info about "pip install pywin32==300"  at https://stackoverflow.com/questions/71614612/importerror-dll-load-failed-while-importing-shell

**Comment by enzok** [comment]
You are missing vcredist. Download and install from Microsoft.
